@startuml

title arrestoDeSospechosoConOrdenSecuencia

Actor User
User -> ":Policia" : entrarEdificio(e :Edificio)
Activate ":Policia"

":Policia" -> ":Mapa" : entrarEdificio(:Reloj , e :Edificio)
activate ":Mapa"

":Mapa" --> ":Policia" : pista_e
deactivate ":Mapa"

":Policia" -> ":Policia": p.pista = pista_e

":Policia" -> ":Caso" : controlArresto(actual :Destino, pista_e :Pista, :Policia)
activate ":Caso"

":Caso" -> ":RutaDeEscape" : controlArresto(actual :Destino, pista_e :Pista, :Policia, :Caso)
activate ":RutaDeEscape"

group case [actual == rutaDeEscape.ultima]

    ":RutaDeEscape" -> "pista_e :Pista": sobreescribir("Sospechoso visto recientemente")
    activate "pista_e :Pista"

    "pista_e :Pista" --> ":RutaDeEscape"
    deactivate "pista_e :Pista"

    group case [segunda entrada a ultimo destino]

        ":RutaDeEscape" -> ":Caso" : arresteSospechoso(:Policia)

        ":Caso" -> ":Policia" : sumarArresto()
        note right: La orden de arresto es correcta

        ":Policia" --> ":Caso"

        ":Caso" --> ":RutaDeEscape"

    end

end

":RutaDeEscape" --> ":Caso"
deactivate ":RutaDeEscape"

":Caso" --> ":Policia"
deactivate ":Caso"

":Policia" --> User
deactivate ":Policia"

@enduml