@startuml

Actor User

User -> ":Policia" : emitirOrdenDeArresto(p1 :Pista, p2 :Pista, p3 :Pista, p4 :Pista, p5 :Pista)
Activate ":Policia"

":Policia" -> ":Caso" : buscarSospechosos(p1 :Pista, p2 :Pista, p3 :Pista, p4 :Pista, p5 :Pista)
activate ":Caso"

":Caso" --> ":Policia" : sospechoso :Sospechoso
deactivate ":Caso"

group case [cantidadSospechosos = 1]

    ":Policia" -> ":Caso" : emitirOrden(sospechoso :Sospechoso)
    activate ":Caso"

    ":Caso" -> "ladronReal :Sospechoso" : coincideCon(sospechoso :Sospechoso)
    activate "ladronReal :Sospechoso"

    "ladronReal :Sospechoso" --> ":Caso" : :False
    deactivate "ladronReal :Sospechoso"

    ":Caso" --> ":Policia"
    deactivate ":Caso"

end

":Policia" --> User
deactivate ":Policia"

@enduml