@startuml

title emitirOrdenDeArrestoFallaPorDescripcionNoUnica

Actor User

User -> ":Policia" : emitirOrdenDeArresto(p1 :Pista, p2 :Pista)
Activate ":Policia"

":Policia" -> ":Caso" : buscarSospechosos(p1 :Pista, p2 :Pista)
activate ":Caso"

":Caso" --> ":Policia" : s1 :Sospechoso, s1 :Sospechoso
deactivate ":Caso"

group case [cantidadSospechosos != 1]

    ":Policia" -> ":Reloj" : aumentarHoras(3)
    activate ":Reloj"

    ":Reloj" --> ":Policia"
    deactivate ":Reloj"

    ":Policia" --> User
    deactivate ":Policia"

end

@enduml