@startuml

title edificioEntrarSecuencia

Actor User

User -> "p :Policia" : entrarEdificio(e :Edificio)
Activate "p :Policia"

"p :Policia" -> ":Mapa" : entrarEdificio(:Reloj , e :Edificio)
activate ":Mapa"

":Mapa" -> "actual :Destino" : entrarEdificio(:Reloj , e :Edificio)
activate "actual :Destino"

"actual :Destino" -> "e :Edificio" : entrar(:Reloj)
activate "e :Edificio"

"e :Edificio" -> ":PrimerEntrada" : demoraTemporal(:Reloj)
activate ":PrimerEntrada"

":PrimerEntrada" -> ":Reloj" : aumentarHoras(1)
activate ":Reloj"

":Reloj" --> ":PrimerEntrada"
deactivate ":Reloj"

":PrimerEntrada" --> "e :Edificio" : :SegundaEntrada
deactivate ":PrimerEntrada"

"e :Edificio" -> "e :Edificio" : actualizarDemorador(:SegundaEntrada)

"e :Edificio" --> "actual :Destino" : pista_e
deactivate "e :Edificio"

"actual :Destino" --> ":Mapa" : pista_e
deactivate "actual :Destino"

":Mapa" --> "p :Policia" : pista_e
deactivate ":Mapa"

"p :Policia" -> "p :Policia": p.pista = pista_e

"p :Policia" --> User
deactivate "p :Policia"

@enduml