@startuml

Actor User

User -> ":Policia" : entrarEdificio(e :Edificio)
Activate ":Policia"

":Policia" -> ":Mapa" : entrarEdificio(e :Edificio)
activate ":Mapa"

":Mapa" -> "actual :Destino" : entrarEdificio(e :Edificio)
activate "actual :Destino"

"actual :Destino" -> "e :Edificio" : entrar()
activate "e :Edificio"

"e :Edificio" -> ":Pista" : mostrarPista()
activate ":Pista"

":Pista" --> "e :Edificio"
deactivate ":Pista"

"e :Edificio" -> ":ControladorEntradas" : demoraTemporal()
activate ":ControladorEntradas"

":ControladorEntradas" --> "e :Edificio" : horasGastadas
deactivate ":ControladorEntradas"

"e :Edificio" --> "actual :Destino" : horasGastadas
deactivate "e :Edificio"

"actual :Destino" --> ":Mapa" : horasGastadas
deactivate "actual :Destino"

":Mapa" --> ":Policia" : horasGastadas
deactivate ":Mapa"

":Policia" -> ":Reloj" : aumentarHoras( horasGastadas )
activate ":Reloj"

":Reloj" --> ":Policia"
deactivate ":Reloj"

":Policia" --> User
deactivate ":Policia"

@enduml