@startuml

Actor User

User -> ":Policia" : viajar(final :Destino)
Activate ":Policia"

":Policia" -> ":Mapa" : viajar(final :Destino)
activate ":Mapa"

":Mapa" -> "actual :Destino" : distanciaCon(final :Destino)
activate "actual :Destino"

"actual :Destino" -> "final :Destino" : obtenerCoordenadas()
activate "final :Destino"

"final :Destino" --> "actual :Destino" : coor_final :Coordenadas
deactivate "final :Destino"

"actual :Destino" -> "actual :Coordenadas" : distancia(coor_final :Coordenadas)
activate "actual :Coordenadas"

"actual :Coordenadas" --> "actual :Destino" : distancia
deactivate "actual :Coordenadas"

"actual :Destino" --> ":Mapa" : distancia
deactivate "actual :Destino"

":Mapa" -> ":Mapa" : actualizarActual(final :Destino)

":Mapa" --> ":Policia" : distancia
deactivate ":Mapa"

":Policia" -> ":Rango" : demoraPorDistancia( distancia , :Reloj )
activate ":Rango"

":Rango" --> ":Reloj" : aumentarHoras(horasGastadas)
activate ":Reloj"

":Reloj" --> ":Rango"
deactivate ":Reloj"

":Rango" --> ":Policia"
deactivate ":Rango"

":Policia" --> User
deactivate ":Policia"

@enduml