@startuml

Actor User

User -> ":Policia" : viajar(d :Destino)
Activate ":Policia"

":Policia" -> ":Mapa" : viajar(d :Destino)
activate ":Mapa"

":Mapa" -> ":CalculadorDistancias" : distancia(coordenadas)
activate ":CalculadorDistancias"

":CalculadorDistancias" --> ":Mapa" : distancia
deactivate ":CalculadorDistancias"

":Mapa" -> ":Mapa" : actualizarActual(d :Destino)

":Mapa" --> ":Policia" : distancia
deactivate ":Mapa"

":Policia" -> ":Rango" : demoraPorDistancia( distancia )
activate ":Rango"

":Rango" --> ":Policia" : horasGastadas
deactivate ":Rango"

":Policia" -> ":Reloj" : aumentarHoras( horasGastadas )
activate ":Reloj"

":Reloj" --> ":Policia"
deactivate ":Reloj"

":Policia" --> User
deactivate ":Policia"

@enduml